### PR TITLE
Fix transaction signing for transactions with empty arrays

### LINKED ISSUE #8: setDelegation icx_sendTransaction with delegations: [] returns error
I have a function which uses `IconBuilder.CallTransactionBuilder` to create a `setDelegation` transaction:

```js
function setDelegations(wallet, delegations) {
  const builder = new IconBuilder.CallTransactionBuilder();
  const setDelegationCall = builder
    .nid(network.nid)
    .from(wallet.getAddress())
    .to(SCORE_INSTALL_ADDRESS)
    .method('setDelegation')
    .params({ delegations: delegationsToSend })
    .stepLimit(IconConverter.toBigNumber(1000000))
    .version(API_VERSION)
    .timestamp(Date.now() * 1000)
    .build();
  const signedTransaction = new SignedTransaction(setDelegationCall, wallet);
  return iconService.sendTransaction(signedTransaction).execute();
}
```

This works fine when I pass a list of delegations, but if I pass an empty list of delegations (`.params({ delegations: [] })`), it returns an error:

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32600,
    "message": "fail tx invalid signature"
  },
  "id": 1571108150709
}
```

I can achieve the desired result by passing a list of delegations with `value: 0x0` and it works, but the docs (https://www.icondev.io/docs/icon-json-rpc-v3#section-setdelegation) give an example of setting `delegations: []` for "Request to revoke all delegations", so it seems like it should work.

Is there something I'm missing or doing wrong? I'm assuming this is an issue with the JSON RPC API, not this JS library specifically. Please let me know if I should ask this question elsewhere.

### PR DESCRIPTION
**Pull request by bkbooth**
Only append '.' between array items in `arrTraverse`.

Fixes #8

### CODE REVIEW

**Comment by bkbooth** [comment]
Should I include the rebuilt *.min.js files in this PR? Or do you have an automated process that will rebuild after this gets merged?

**Comment by bkbooth** [comment]
I've confirmed this is working now. Transaction:

```json
{
  "jsonrpc": "2.0",
  "id": 1571195077272,
  "method": "icx_sendTransaction",
  "params": {
    "to": "cx0000000000000000000000000000000000000000",
    "from": "hxc28387c8801185231882022fe90d0b6cc8d6ac7c",
    "stepLimit": "0xf4240",
    "nid": "0x50",
    "version": "0x3",
    "timestamp": "0x594fe5c73f2e0",
    "dataType": "call",
    "data": {
      "method": "setDelegation",
      "params": {
        "delegations": []
      }
    },
    "signature": "fdMtcoBDzxoUm6dRrHStEbjhwCzyMYx/69fBBisjjRwrPkdwmPrYg5hg/3E1os7OxRwxKLyD3qR8tpv7+fFfdwA="
  }
}
```

Response:

```json
{
  "jsonrpc": "2.0",
  "result": "0x9c8930fd144c66e0486509dca8158770c3f219a33ddbb1bcc626b1efca3c60cd",
  "id": 1571195077272
}
```

File: lib/data/Util.js [hunk 1]
```diff
@@ -111,9 +111,11 @@ export function arrTraverse(arr) {
 			default:
 				break;
 		}
-		result += '.';
+
+		if (j < arr.length - 1) {
+			result += '.';
+		}
```
Comment (sink772) [inline lib/data/Util.js]: Checking `j' in every iteration seems to be inefficient.
How about leaving this line unchanged and modifying the original line 116 as the following?
```
    if (result.endsWith(".")) {
        result = result.slice(0, -1);
    }
```

Comment (bkbooth) [reply lib/data/Util.js]: I considered something like this, but in the end I thought not adding the extra '.' at all was cleaner. Happy to go with this approach though, I'll push a change shortly
